version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MINIO_ACCESS_KEY: YEv9LUqnG9Q87TPj7cbI
      MINIO_SECRET_KEY: 62ijOcUlbkIKs20jm0l8TiZUYtHC3ESDkcuOVErZ
    ports:
      - "5000:5000"
    depends_on:
      - minio
    volumes:
      - .:/app

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: YEv9LUqnG9Q87TPj7cbI
      MINIO_SECRET_KEY: 62ijOcUlbkIKs20jm0l8TiZUYtHC3ESDkcuOVErZ
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    command: server /data

volumes:
  minio-data:
